name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Swift ${{ matrix.swift }}
    runs-on: macos-latest
    strategy:
      matrix:
        swift: ["5.6", "5.7", "5.8", "5.9"]
    steps:
      - uses: actions/checkout@v4
      
      - uses: swift-actions/setup-swift@v1
        with:
          swift-version: ${{ matrix.swift }}

      - name: Build
        run: swift build

      - name: Run tests
        run: swift test